const $ = selector => document.querySelector(selector);
const grid = $('.reels-grid');
const template = $('#reelTemplate');
const format = value => new Intl.NumberFormat('ru-RU', { notation: 'compact', maximumFractionDigits: 1 }).format(value || 0);
const cover = title => `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 700 900"><rect width="700" height="900" fill="#d7b59f"/><circle cx="560" cy="200" r="210" fill="#f5e2be" opacity=".74"/><path d="M0 630 C180 470 350 810 700 560V900H0Z" fill="#fff7ef" opacity=".86"/><text x="72" y="740" font-family="Georgia, serif" font-size="58" font-style="italic" fill="#292521">${title}</text></svg>`)}`;
async function api(path, options = {}) { const response = await fetch(path, { headers: { 'Content-Type': 'application/json', ...(options.headers || {}) }, ...options }); if (response.status === 204) return null; const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Не удалось выполнить запрос'); return data; }
function draw(reels) { grid.innerHTML = ''; if (!reels.length) { grid.innerHTML = '<p class="empty-state">Пока нет рилсов. Добавьте первую ссылку из Instagram.</p>'; return; } reels.forEach(reel => { const card = template.content.cloneNode(true); card.querySelector('img').src = reel.coverUrl || cover(reel.title); card.querySelector('img').alt = reel.title; card.querySelector('h3').textContent = reel.title; card.querySelector('.date').textContent = new Date(reel.publishedAt).toLocaleDateString('ru-RU', { day: 'numeric', month: 'long', year: 'numeric' }); card.querySelector('.duration').textContent = reel.duration ? `0:${String(reel.duration).padStart(2, '0')}` : 'REEL'; card.querySelector('.view-count').textContent = reel.formattedViews || format(reel.views); card.querySelector('.like-count').textContent = reel.formattedLikes || format(reel.likes); card.querySelector('.comment-count').textContent = reel.comments || 0; const update = card.querySelector('.more'); update.title = reel.syncStatus === 'failed' ? (reel.syncError || 'Ошибка синхронизации') : 'Обновить данные'; update.onclick = async () => { try { update.textContent = '…'; await api(`/api/reels/${reel.id}/sync`, { method: 'POST' }); await loadDashboard(); } catch (error) { alert(error.message); update.textContent = '•••'; } }; grid.append(card); }); }
async function loadDashboard() { const { analytics, reels, accounts } = await api('/api/dashboard'); $('#viewsTotal').textContent = format(analytics.views); $('#engagement').textContent = `${analytics.engagement}%`; $('#likesTotal').textContent = format(analytics.likes); $('#reelsTotal').textContent = analytics.reels; $('#userHandle').textContent = accounts[0]?.handle || 'Instagram не подключён'; $('#freshnessText').textContent = analytics.updatedAt ? `Данные обновлены ${new Date(analytics.updatedAt).toLocaleString('ru-RU')}` : 'Добавьте первый рилс для синхронизации'; draw(reels); }
function showApp(user) { $('#loginScreen').hidden = true; $('#userName').textContent = user.name; $('#avatar').textContent = user.name.split(' ').map(word => word[0]).join('').slice(0, 2).toUpperCase(); $('#greeting').textContent = `ДОБРОЕ УТРО, ${user.name.split(' ')[0].toUpperCase()} ✦`; loadDashboard().catch(error => alert(error.message)); }
$('#loginForm').addEventListener('submit', async event => { event.preventDefault(); const error = $('#loginError'); error.textContent = ''; try { const data = await api('/api/auth/login', { method: 'POST', body: JSON.stringify({ email: $('#email').value, password: $('#password').value }) }); showApp(data.user); } catch (err) { error.textContent = err.message; } });
$('#logout').onclick = async () => { await api('/api/auth/logout', { method: 'POST' }); $('#loginScreen').hidden = false; };
$('#openAdd').onclick = () => $('#addDialog').showModal(); $('#openSettings').onclick = () => $('#settingsDialog').showModal();
$('#reelForm').addEventListener('submit', async event => { event.preventDefault(); const button = event.currentTarget.querySelector('.add-btn'); button.disabled = true; button.textContent = 'Добавляем и синхронизируем…'; try { await api('/api/reels', { method: 'POST', body: JSON.stringify({ sourceUrl: $('#reelUrl').value }) }); $('#reelUrl').value = ''; $('#addDialog').close(); await loadDashboard(); } catch (error) { alert(error.message); } finally { button.disabled = false; button.textContent = 'Подтянуть данные →'; } });
document.querySelectorAll('.switcher button').forEach(button => button.addEventListener('click', () => { $('.switcher .selected').classList.remove('selected'); button.classList.add('selected'); grid.classList.toggle('list-mode', button.dataset.view === 'list'); }));
api('/api/auth/me').then(data => showApp(data.user)).catch(() => { $('#loginScreen').hidden = false; });
