const $ = selector => document.querySelector(selector);
const $$ = selector => document.querySelectorAll(selector);
const grid = $('.reels-grid');
const template = $('#reelTemplate');
let dashboardReels = [];
let visibleReels = 6;
const format = value => new Intl.NumberFormat('ru-RU', { notation: 'compact', maximumFractionDigits: 1 }).format(value || 0);
const cover = title => `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 700 900"><rect width="700" height="900" fill="#d7b59f"/><circle cx="560" cy="200" r="210" fill="#f5e2be" opacity=".74"/><path d="M0 630 C180 470 350 810 700 560V900H0Z" fill="#fff7ef" opacity=".86"/><text x="72" y="740" font-family="Georgia, serif" font-size="58" font-style="italic" fill="#292521">${title}</text></svg>`)}`;
async function api(path, options = {}) { const response = await fetch(path, { headers: { 'Content-Type': 'application/json', ...(options.headers || {}) }, ...options }); if (response.status === 204) return null; const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Не удалось выполнить запрос'); return data; }
function showMessage(title, message, tone = 'success') { $('#messageTitle').textContent = title; $('#messageText').textContent = message; $('#messageKicker').textContent = tone === 'error' ? 'НЕ УДАЛОСЬ ВЫПОЛНИТЬ' : 'ГОТОВО'; $('#messageIcon').textContent = tone === 'error' ? '!' : '✓'; $('#messageDialog').classList.toggle('is-error', tone === 'error'); $('#messageDialog').showModal(); }
function renderRhythm(rhythm) { const values = rhythm?.dayViews || Array(7).fill(0); const max = Math.max(...values, 0); $('#rhythmBars').innerHTML = values.map((value, index) => `<i class="${max && value === max ? 'peak' : ''}" style="height:${max ? Math.max(8, Math.round(value / max * 100)) : 8}%" title="${['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Вс'][index]}: ${format(value)} просмотров" aria-label="${format(value)} просмотров"></i>`).join(''); $('#rhythmPeak').textContent = max ? `${format(max)} максимум` : 'Нет данных'; $('#rhythmSummary').textContent = rhythm?.bestDay ? `Лучше всего смотрят рилсы, опубликованные в ${rhythm.bestDay}. Столбцы построены по фактическим просмотрам всех ваших публикаций.` : 'Добавьте и синхронизируйте рилсы — здесь появится распределение реальных просмотров по дням публикации.'; }
function renderNotifications(reels) { const failed = reels.filter(reel => reel.syncStatus === 'failed'); $('#openNotifications i').hidden = !failed.length; $('#notificationsList').innerHTML = failed.length ? failed.map(reel => `<article class="notification warning"><span>!</span><div><b>Не удалось обновить рилс</b><p>${reel.title}: ${reel.syncError || 'попробуйте ещё раз'}</p></div></article>`).join('') : '<div class="notifications-empty"><span>✦</span><b>Всё под контролем</b><p>Новых уведомлений пока нет. Здесь появятся результаты импорта и ошибки синхронизации.</p></div>'; }
function draw(reels) { grid.innerHTML = ''; const shown = reels.slice(0, visibleReels); $('#showMore').hidden = reels.length <= visibleReels; if (!reels.length) { grid.innerHTML = '<p class="empty-state">Пока нет рилсов. Подключите Instagram-профиль или добавьте первую ссылку.</p>'; return; } shown.forEach(reel => { const card = template.content.cloneNode(true); card.querySelector('img').src = reel.coverUrl || cover(reel.title); card.querySelector('img').alt = reel.title; card.querySelector('h3').textContent = reel.title; card.querySelector('.date').textContent = new Date(reel.publishedAt).toLocaleDateString('ru-RU', { day: 'numeric', month: 'long', year: 'numeric' }); card.querySelector('.duration').textContent = reel.duration ? `0:${String(Math.round(reel.duration)).padStart(2, '0')}` : 'REEL'; card.querySelector('.view-count').textContent = reel.formattedViews || format(reel.views); card.querySelector('.like-count').textContent = reel.formattedLikes || format(reel.likes); card.querySelector('.comment-count').textContent = reel.comments || 0; const save = card.querySelector('.save'); save.onclick = () => { save.classList.toggle('saved'); save.textContent = save.classList.contains('saved') ? '♥' : '♡'; }; const update = card.querySelector('.more'); update.title = reel.syncStatus === 'failed' ? (reel.syncError || 'Ошибка синхронизации') : 'Обновить данные'; update.onclick = async () => { try { update.textContent = '…'; await api(`/api/reels/${reel.id}/sync`, { method: 'POST' }); await loadDashboard(); showMessage('Данные обновлены', 'Показатели рилса успешно синхронизированы.'); } catch (error) { showMessage('Не удалось обновить', error.message, 'error'); update.textContent = '•••'; } }; grid.append(card); }); }
async function loadDashboard() { const { analytics, reels, accounts } = await api('/api/dashboard'); dashboardReels = reels; $('#viewsTotal').textContent = format(analytics.views); $('#engagement').textContent = `${analytics.engagement}%`; $('#likesTotal').textContent = format(analytics.likes); $('#reelsTotal').textContent = analytics.reels; $('#userHandle').textContent = accounts[0]?.handle || 'Instagram не подключён'; $('#accountHandle').value = accounts[0]?.handle || ''; $('#freshnessText').textContent = analytics.updatedAt ? `Данные обновлены ${new Date(analytics.updatedAt).toLocaleString('ru-RU')}` : 'Добавьте профиль или рилс для синхронизации'; renderRhythm(analytics.rhythm); renderNotifications(reels); draw(reels); }
function showApp(user) { $('#loginScreen').hidden = true; $('#userName').textContent = user.name; $('#avatar').textContent = user.name.split(' ').map(word => word[0]).join('').slice(0, 2).toUpperCase(); $('#greeting').textContent = `ДОБРОЕ УТРО, ${user.name.split(' ')[0].toUpperCase()} ✦`; loadDashboard().catch(error => showMessage('Не удалось загрузить кабинет', error.message, 'error')); }
$('#loginForm').addEventListener('submit', async event => { event.preventDefault(); const error = $('#loginError'); error.textContent = ''; try { showApp((await api('/api/auth/login', { method: 'POST', body: JSON.stringify({ email: $('#email').value, password: $('#password').value }) })).user); } catch (err) { error.textContent = err.message; } });
window.onTelegramAuth = async telegramUser => { const error = $('#loginError'); error.textContent = ''; try { showApp((await api('/api/auth/telegram/login', { method: 'POST', body: JSON.stringify(telegramUser) })).user); } catch (err) { error.textContent = err.message; } };
api('/api/auth/telegram/config').then(({ botUsername }) => { const script = document.createElement('script'); script.src = 'https://telegram.org/js/telegram-widget.js?22'; script.async = true; script.dataset.telegramLogin = botUsername; script.dataset.size = 'large'; script.dataset.onauth = 'onTelegramAuth(user)'; script.dataset.requestAccess = 'write'; $('#telegramLogin').append(script); }).catch(() => { $('#telegramLogin').textContent = 'Вход через Telegram пока не настроен'; });
$('#logout').onclick = async () => { await api('/api/auth/logout', { method: 'POST' }); $('#loginScreen').hidden = false; };
$('#openAdd').onclick = () => $('#addDialog').showModal(); $('#openSettings').onclick = () => $('#settingsDialog').showModal(); $('#openSettingsMobile').onclick = () => $('#settingsDialog').showModal(); $('#openNotifications').onclick = () => $('#notificationsDialog').showModal(); $('#messageClose').onclick = () => $('#messageDialog').close();
$$('[data-close]').forEach(button => button.onclick = () => button.closest('dialog').close());
$('#reelForm').addEventListener('submit', async event => { event.preventDefault(); const button = event.currentTarget.querySelector('.add-btn'); button.disabled = true; button.textContent = 'Добавляем и синхронизируем…'; try { await api('/api/reels', { method: 'POST', body: JSON.stringify({ sourceUrl: $('#reelUrl').value }) }); $('#reelUrl').value = ''; $('#addDialog').close(); visibleReels = Math.max(visibleReels, dashboardReels.length + 1); await loadDashboard(); showMessage('Рилс добавлен', 'Мы сохранили рилс и обновили доступные показатели.'); } catch (error) { showMessage('Не удалось добавить рилс', error.message, 'error'); } finally { button.disabled = false; button.textContent = 'Подтянуть данные →'; } });
$('#settingsForm').addEventListener('submit', async event => { event.preventDefault(); const button = $('#syncAccount'); button.disabled = true; button.textContent = 'Ищем рилсы…'; try { const data = await api('/api/accounts/import', { method: 'POST', body: JSON.stringify({ handle: $('#accountHandle').value, limit: Number($('#reelsLimit').value) }) }); $('#settingsDialog').close(); showMessage('Профиль подключён', `Получено публикаций: ${data.received}. Добавлено: ${data.created}, обновлено: ${data.updated}.`); visibleReels = Math.max(visibleReels, data.created + data.updated); await loadDashboard(); } catch (error) { showMessage('Не удалось подключить профиль', error.message, 'error'); } finally { button.disabled = false; button.textContent = 'Подключить профиль и подтянуть рилсы →'; } });
$$('.switcher button').forEach(button => button.addEventListener('click', () => { $('.switcher .selected').classList.remove('selected'); button.classList.add('selected'); grid.classList.toggle('list-mode', button.dataset.view === 'list'); }));
$('#showMore').onclick = () => { visibleReels += 6; draw(dashboardReels); };
const cookieBanner = $('#cookieBanner');
function cookieNoticeAccepted() { try { return localStorage.getItem('pif_cookie_notice') === '1'; } catch { return false; } }
function dismissCookieNotice() { try { localStorage.setItem('pif_cookie_notice', '1'); } catch {} cookieBanner.hidden = true; cookieBanner.setAttribute('aria-hidden', 'true'); }
if (!cookieNoticeAccepted()) { cookieBanner.hidden = false; cookieBanner.removeAttribute('aria-hidden'); }
$('#acceptCookies').addEventListener('click', dismissCookieNotice);
api('/api/auth/me').then(data => showApp(data.user)).catch(() => { $('#loginScreen').hidden = false; });
